### ISSUE TITLE
複製空密碼

### ISSUE THREAD

**Issue by ian5421tw** [overdoignism/Final-Account-Defense-Barrier#1]
若創建的新帳號在未輸入密碼的情況下保存，按下複製密碼後會提示無法執行，若選擇繼續執行整個程式無反應

**Comment by overdoignism** [comment]
Clipboard.SetText() 不能複製空字串所致.... 我晚點會加上這部分的防呆。

**Comment by overdoignism** [comment]
v0.9.8472.42289 已修正
